#!/bin/sh
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A -0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0.6
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0.7
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0.8
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 0.9
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 1.0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 1.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 1.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 1.3
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 1.4
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.3 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.2 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1.1 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -1 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.9 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.8 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.7 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.6 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.5 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.4 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.3 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.2 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V -0.1 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.1 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.2 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.3 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.4 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.5 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.6 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.7 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.8 DC1A 1.5
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC1V 0.9 DC1A 1.5


run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A -0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A -0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A -0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A -0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A -0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A 0
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A 0.05
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A 0.1
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A 0.15
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A 0.2
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.25 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.2 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.15 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.1 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V -0.05 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.05 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.1 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.15 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.2 DC2A 0.25
run.py --model ewkDM --process ttZ_ll --makeGridpack --calcXSec --couplings DC2V 0.25 DC2A 0.25

